name: Commit
run-name: ${{ github.actor }} está enviando um novo commit

on:
  push:
    branches:
      - feat/post
      - feat/workflows

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório e trocando para a branch correta
        uses: actions/checkout@v2 

      - name: Instalando o Node.js versão 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Intalando o Jest
        run: npm install --save-dev jest

      - name: Rodando os testes
        run: npx jest

  test-qualidade:
    runs-on: ubuntu-latest
    needs: build-and-tests

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v2

      - name: Instalando o Node.js versão 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'

      - name: Instalando dependências do projeto
        run: npm install

      - name: Verificando cobertura de código com Jest
        run: npx jest --coverage