name: Commit
run-name: ${{ github.actor }} está enviando um novo commit

on:
  push:
    branches:
      - feat/post
      - feat/workflows

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório e trocando para a branch correta
        uses: actions/checkout@v2

      - name: Instalando o Node.js versão 21
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Intalando o Jest
        run: npm install --save-dev jest

      - name: Instalando o Supertest
        run: npm install supertest

      - name: Instalando dependências do projeto
        run: npm install

      - name: Ajustar permissões de execução do Jest
        run: chmod +x node_modules/.bin/jest

      - name: Rodando os testes
        run: npx jest

  test-qualidade:
    runs-on: ubuntu-latest
    needs: build-and-tests

    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v2

      - name: Instalando o Node.js versão 21
        uses: actions/setup-node@v3
        with:
          node-version: "21"

      - name: Instalando dependências do projeto
        run: npm install

      - name: Verificando cobertura de código com Jest
        run: npx jest --coverage

  sonarcloud:
    runs-on: ubuntu-latest
    needs: test-qualidade
    steps:
      - name: Clonando o repositório
        uses: actions/checkout@v2

      - name: Configurando o SonarCloud
        uses: sonarsource/sonarcloud-github-action@v2
        with:
          entryPoint: "sonar-scanner"
          args: |
            -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
            -Dsonar.organization=${{ secrets.SONAR_ORG }}
            -Dsonar.branch.name=${{ github.ref_name == 'refs/heads/main' && 'main' || github.ref_name }}
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}

      - name: Executando a análise no SonarCloud
        run: npx sonar-scanner
