name: Pull request
run-name: ${{ github.actor }} está enviando um novo pull request

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Clonando o repositório e trocando para a branch correta
        uses: actions/checkout@v2

      - name: Instalando o Node.js versão 21
        uses: actions/setup-node@v3
        with:
          node-version: '21'  

      - name: Instalando dependências do projeto
        run: npm install 

      - name: Ajustar permissões de execução do Jest
        run: chmod +x node_modules/.bin/jest

      - name: Rodando os testes
        run: npx jest

